BEGIN TRANSACTION
GO

IF EXISTS (
	SELECT	*
	FROM	sys.objects
	WHERE	object_id = OBJECT_ID(N'dbo.FileManagerKey')
	AND		TYPE IN (N'U')
)
BEGIN
	DROP TABLE dbo.FileManagerKey;
END
GO

CREATE TABLE dbo.FileManagerKey(
	fmKeyId		INT				NOT NULL IDENTITY(1,1)
	,fmKeyName	VARCHAR(50)		NOT NULL
	,fmKeyDesc	VARCHAR(255)	NULL
	,fmKeyPath	VARCHAR(255)	NULL
	,PRIMARY KEY CLUSTERED (
		fmKeyId ASC
	) 
	WITH (
		PAD_INDEX = OFF
		,STATISTICS_NORECOMPUTE = OFF
		,IGNORE_DUP_KEY = OFF
		,ALLOW_ROW_LOCKS = ON
		,ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
) ON [PRIMARY]
GO

COMMIT
