BEGIN TRANSACTION
GO

-----------
-- MODEL --
-----------
INSERT INTO dbo.FmLkupMimeType 
	(fmMimeTypeName, fmMimeType)
VALUES
	('example', 'model/example')
	,('iges', 'model/iges')
	,('mesh', 'model/mesh')
	,('vnd.collada+xml', 'model/vnd.collada+xml')
	,('vnd.dwf', 'model/vnd-dwf')
	,('vnd.flatland.3dml', 'model/vnd.flatland.3dml')
	,('vnd.gdl', 'model/vnd.gdl')
	,('vnd.gs-gdl', 'model/vnd.gs-gdl')
	,('vnd.gtw', 'model/vnd.gtw')
	,('vnd.moml+xml', 'model/vnd.moml+xml')
	,('vnd.mts', 'model/vnd.mts')
	,('vnd.opengex', 'model/vnd.opengex')
	,('vnd.parasolid.transmit.binary', 'model/vnd.parasolid.transmit-binary')
	,('vnd.parasolid.transmit.text', 'model/vnd.parasolid.transmit-text')
	,('vnd.valve.source.compiled-map', 'model/vnd.valve.source.compiled-map')
	,('vnd.vtu', 'model/vnd.vtu')
	,('vrml', 'model/vrml')
	,('x3d-vrml', 'model/x3d-vrml')
	,('x3d+fastinfoset', 'model/x3d+fastinfoset')
	,('x3d+xml', 'model/x3d+xml')
;

---------------
-- MULTIPART --
---------------
INSERT INTO dbo.FmLkupMimeType 
	(fmMimeTypeName, fmMimeType)
VALUES
	('alternative', 'multipart/alternative')
	,('appledouble', 'multipart/appledouble')
	,('byteranges', 'multipart/byteranges')
	,('digest', 'multipart/digest')
	,('encrypted', 'multipart/encrypted')
	,('example', 'multipart/example')
	,('form-data', 'multipart/form-data')
	,('header-set', 'multipart/header-set')
	,('mixed', 'multipart/mixed')
	,('parallel', 'multipart/parallel')
	,('related', 'multipart/related')
	,('report', 'multipart/report')
	,('signed', 'multipart/signed')
	,('voice-message', 'multipart/voice-message')
	,('x-mixed-replace', 'multipart/x-mixed-replace')
;

----------
-- TEXT --
----------
INSERT INTO dbo.FmLkupMimeType 
	(fmMimeTypeName, fmMimeType)
VALUES
	('1d-interleaved-parityfec', 'text/1d-interleaved-parityfec')
	,('cache-manifest', 'text/cache-manifest')
	,('calendar', 'text/calendar')
	,('css', 'text/css')
	,('csv', 'text/csv')
	,('csv-schema', 'text/csv-schema')
	,('directory - DEPRECATED by RFC6350', 'text/directory')
	,('dns', 'text/dns')
	,('ecmascript - OBSOLETED in favor of application/ecmascript', 'text/ecmascript')
	,('encaprtp', 'text/encaprtp')
	,('enriched', 'text/enriched')
	,('example', 'text/example')
	,('fwdred', 'text/fwdred')
	,('grammar-ref-list', 'text/grammar-ref-list')
	,('html', 'text/html')
	,('javascript - OBSOLETED in favor of application/javascript', 'text/javascript')
	,('jcr-cnd', 'text/jcr-cnd')
	,('markdown (TEMPORARY - registered 2014-11-11, expires 2015-11-11)', 'text/markdown')
	,('mizar', 'text/mizar')
	,('n3', 'text/n3')
	,('parameters', 'text/parameters')
	,('parityfec', 'text/parityfec')
	,('plain', 'text/plain')
	,('provenance-notation', 'text/provenance-notation')
	,('prs.fallenstein.rst', 'text/prs.fallenstein.rst')
	,('prs.lines.tag', 'text/prs.lines.tag')
	,('raptorfec', 'text/raptorfec')
	,('RED', 'text/RED')
	,('rfc822-headers', 'text/rfc822-headers')
	,('richtext', 'text/richtext')
	,('rtf', 'text/rtf')
	,('rtp-enc-aescm128', 'text/rtp-enc-aescm128')
	,('rtploopback', 'text/rtploopback')
	,('rtx', 'text/rtx')
	,('sgml', 'text/SGML')
	,('t140', 'text/t140')
	,('tab-separated-values', 'text/tab-separated-values')
	,('troff', 'text/troff')
	,('turtle', 'text/turtle')
	,('ulpfec', 'text/ulpfec')
	,('uri-list', 'text/uri-list')
	,('vcard', 'text/vcard')
	,('vnd.a', 'text/vnd-a')
	,('vnd.abc', 'text/vnd.abc')
	,('vnd.curl', 'text/vnd-curl')
	,('vnd.debian.copyright', 'text/vnd.debian.copyright')
	,('vnd.DMClientScript', 'text/vnd.DMClientScript')
	,('vnd.dvb.subtitle', 'text/vnd.dvb.subtitle')
	,('vnd.esmertec.theme-descriptor', 'text/vnd.esmertec.theme-descriptor')
	,('vnd.fly', 'text/vnd.fly')
	,('vnd.fmi.flexstor', 'text/vnd.fmi.flexstor')
	,('vnd.graphviz', 'text/vnd.graphviz')
	,('vnd.in3d.3dml', 'text/vnd.in3d.3dml')
	,('vnd.in3d.spot', 'text/vnd.in3d.spot')
	,('vnd.IPTC.NewsML', 'text/vnd.IPTC.NewsML')
	,('vnd.IPTC.NITF', 'text/vnd.IPTC.NITF')
	,('vnd.latex-z', 'text/vnd.latex-z')
	,('vnd.motorola.reflex', 'text/vnd.motorola.reflex')
	,('vnd.ms-mediapackage', 'text/vnd.ms-mediapackage')
	,('vnd.net2phone.commcenter.command', 'text/vnd.net2phone.commcenter.command')
	,('vnd.radisys.msml-basic-layout', 'text/vnd.radisys.msml-basic-layout')
	,('vnd.si.uricatalogue - OBSOLETED by request', 'text/vnd.si.uricatalogue')
	,('vnd.sun.j2me.app-descriptor', 'text/vnd.sun.j2me.app-descriptor')
	,('vnd.trolltech.linguist', 'text/vnd.trolltech.linguist')
	,('vnd.wap.si', 'text/vnd.wap.si')
	,('vnd.wap.sl', 'text/vnd.wap.sl')
	,('vnd.wap.wml', 'text/vnd.wap-wml')
	,('vnd.wap.wmlscript', 'text/vnd.wap.wmlscript')
	,('xml', 'text/xml')
	,('xml-external-parsed-entity', 'text/xml-external-parsed-entity')
;

-----------
-- VIDEO --
-----------
INSERT INTO dbo.FmLkupMimeType 
	(fmMimeTypeName, fmMimeType)
VALUES
	('1d-interleaved-parityfec', 'video/1d-interleaved-parityfec')
	,('3gpp', 'video/3gpp')
	,('3gpp2', 'video/3gpp2')
	,('3gpp-tt', 'video/3gpp-tt')
	,('BMPEG', 'video/BMPEG')
	,('BT656', 'video/BT656')
	,('CelB', 'video/CelB')
	,('DV', 'video/DV')
	,('encaprtp', 'video/encaprtp')
	,('example', 'video/example')
	,('H261', 'video/H261')
	,('H263', 'video/H263')
	,('H263-1998', 'video/H263-1998')
	,('H263-2000', 'video/H263-2000')
	,('H264', 'video/H264')
	,('H264-RCDO', 'video/H264-RCDO')
	,('H264-SVC', 'video/H264-SVC')
	,('iso.segment', 'video/iso.segment')
	,('JPEG', 'video/JPEG')
	,('jpeg2000', 'video/jpeg2000')
	,('mj2', 'video/mj2')
	,('MP1S', 'video/MP1S')
	,('MP2P', 'video/MP2P')
	,('MP2T', 'video/MP2T')
	,('mp4', 'video/mp4')
	,('MP4V-ES', 'video/MP4V-ES')
	,('MPV', 'video/MPV')
	,('mpeg', 'video/mpeg')
	,('mpeg4-generic', 'video/mpeg4-generic')
	,('nv', 'video/nv')
	,('ogg', 'video/ogg')
	,('parityfec', 'video/parityfec')
	,('pointer', 'video/pointer')
	,('quicktime', 'video/quicktime')
	,('raptorfec', 'video/raptorfec')
	,('raw', 'video/raw')
	,('rtp-enc-aescm128', 'video/rtp-enc-aescm128')
	,('rtploopback', 'video/rtploopback')
	,('rtx', 'video/rtx')
	,('SMPTE292M', 'video/SMPTE292M')
	,('ulpfec', 'video/ulpfec')
	,('vc1', 'video/vc1')
	,('vnd.CCTV', 'video/vnd.CCTV')
	,('vnd.dece.hd', 'video/vnd.dece.hd')
	,('vnd.dece.mobile', 'video/vnd.dece.mobile')
	,('vnd.dece.mp4', 'video/vnd.dece-mp4')
	,('vnd.dece.pd', 'video/vnd.dece.pd')
	,('vnd.dece.sd', 'video/vnd.dece.sd')
	,('vnd.dece.video', 'video/vnd.dece.video')
	,('vnd.directv.mpeg', 'video/vnd.directv-mpeg')
	,('vnd.directv.mpeg-tts', 'video/vnd.directv.mpeg-tts')
	,('vnd.dlna.mpeg-tts', 'video/vnd.dlna.mpeg-tts')
	,('vnd.dvb.file', 'video/vnd.dvb.file')
	,('vnd.fvt', 'video/vnd.fvt')
	,('vnd.hns.video', 'video/vnd.hns.video')
	,('vnd.iptvforum.1dparityfec-1010', 'video/vnd.iptvforum.1dparityfec-1010')
	,('vnd.iptvforum.1dparityfec-2005', 'video/vnd.iptvforum.1dparityfec-2005')
	,('vnd.iptvforum.2dparityfec-1010', 'video/vnd.iptvforum.2dparityfec-1010')
	,('vnd.iptvforum.2dparityfec-2005', 'video/vnd.iptvforum.2dparityfec-2005')
	,('vnd.iptvforum.ttsavc', 'video/vnd.iptvforum.ttsavc')
	,('vnd.iptvforum.ttsmpeg2', 'video/vnd.iptvforum.ttsmpeg2')
	,('vnd.motorola.video', 'video/vnd.motorola.video')
	,('vnd.motorola.videop', 'video/vnd.motorola.videop')
	,('vnd.mpegurl', 'video/vnd-mpegurl')
	,('vnd.ms-playready.media.pyv', 'video/vnd.ms-playready.media.pyv')
	,('vnd.nokia.interleaved-multimedia', 'video/vnd.nokia.interleaved-multimedia')
	,('vnd.nokia.videovoip', 'video/vnd.nokia.videovoip')
	,('vnd.objectvideo', 'video/vnd.objectvideo')
	,('vnd.radgamettools.bink', 'video/vnd.radgamettools.bink')
	,('vnd.radgamettools.smacker', 'video/vnd.radgamettools.smacker')
	,('vnd.sealed.mpeg1', 'video/vnd.sealed.mpeg1')
	,('vnd.sealed.mpeg4', 'video/vnd.sealed.mpeg4')
	,('vnd.sealed.swf', 'video/vnd.sealed-swf')
	,('vnd.sealedmedia.softseal.mov', 'video/vnd.sealedmedia.softseal-mov')
	,('vnd.uvvu.mp4', 'video/vnd.uvvu-mp4')
	,('vnd.vivo', 'video/vnd-vivo')
;

COMMIT
